public class clsFacilities {
	public string facility_id { get; set; } 
    public string facility_name { get; set; } 
    public string facility_code { get; set; } 
    public string facility_status { get; set; } 
    public string address_line1 { get; set; } 
    public string address_line2 { get; set; } 
    public string city { get; set; } 
    public string state { get; set; } 
    public string country { get; set; } 
    public string zip_code { get; set; } 
    public string mobile { get; set; } 
    public string office_phone { get; set; } 
    public string is_silhouette { get; set; } 
}