public class ClsPatientPost {    

        public String first_name{get;set;}
        public String last_name{get;set;}
        public String gender{get;set;}
        public String dob{get;set;}
        public String age{get;set;}
        public list<clsPatientBase.facility> facilities{get;set;}
        public String middle_name{get;set;}
        public String record_id{get;set;}
        public String gender_identity{get;set;}
        public String nick_name{get;set;}
        public String suffix{get;set;}
        public String maiden_name{get;set;}
        public String deceased{get;set;}
        public String dod{get;set;}
        public String cause_of_death{get;set;}
        public String linked_patient_id{get;set;}
        public List<clsPatientBase.qualifier> id_qualifiers {get;set;}
        public clsPatientBase.address address {get;set;}
        public String mobile{get;set;}
		public String home_phone{get;set;}		
		public String work_phone{get;set;}		
		public String work_phone_extn{get;set;}		
		public String email{get;set;}		
		public String primary_phone{get;set;}		
		public String emergency_contact_name{get;set;}
        public String emergency_contact_number{get;set;}
        public String emergency_contact_number_extn{get;set;}
        public String emergency_extn{get;set;}
        public list<clsPatientBase.caregiver> caregivers{get;set;}
        public clsPatientBase.guarantor guarantor{get;set;}  
        public String preferred_communication{get;set;}	
        public String email_notification{get;set;}
        public String text_notification{get;set;}
        public String voice_notification{get;set;}
        public String blood_group{get;set;}
        public String language{get;set;}
        public String race{get;set;}
        public String ethnicity{get;set;}   
		public String smoking_status{get;set;}		
		public String marital_status{get;set;}		
		public String employment_status{get;set;}		
		public String sexual_orientation{get;set;}		
		public String mother_first_name{get;set;}		
		public String mother_last_name{get;set;}
        public String is_multiple_birth{get;set;}
		public String birth_order{get;set;}		
		public list<clsPatientBase.category> categories{get;set;}		
		public String introduction{get;set;}		
		public String custom_field_1{get;set;}		
		public String custom_field_2{get;set;}		
		public String custom_field_3{get;set;}		
		public String custom_field_4{get;set;}
		public String custom_field_5{get;set;}		
		public String source_name{get;set;}		
		public String source_value{get;set;}		
		public String payment_source{get;set;}		
		public String payment_start_date{get;set;}		
		public String payment_end_date{get;set;}
        public String rep_first_name{get;set;}
        public String rep_last_name {get;set;}
        public String send_phr_invite {get;set;}
        public String duplicate_check{get;set;}		
	             
     
}